# Generated by Django 5.2 on 2025-04-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='additional_params',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='product',
            name='standard',
        ),
    ]
