# Generated by Django 5.2 on 2025-06-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_additional_params_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='searchcache',
            options={'verbose_name': 'Кэш поиска', 'verbose_name_plural': 'Кэш поиска'},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'verbose_name': 'Поисковый запрос', 'verbose_name_plural': 'Поисковые запросы'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_list_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='X', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(default='X', max_length=50),
        ),
    ]
